# (APPENDIX) Appendix {-} 

# Package Dependencies 

The book depends on the following packages:

```{r is_travis, echo=FALSE}
## Don't generate bib file on travis
is_travis = Sys.getenv("TRAVIS")
is_travis = (is_travis == "true")
pkgs_df = read.csv("extdata/package_list.csv", header=TRUE)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, eval=(!is_travis)}
desc = read.dcf("DESCRIPTION")
headings = dimnames(desc)[[2]]
fields = which(headings %in% c("Depends", "Imports", "Suggests"))
pkgs = paste(desc[fields], collapse = ", ")
pkgs = gsub("\n", " ", pkgs)
pkgs = strsplit(pkgs, ",")[[1]]
pkgs = gsub(" ", "", pkgs)
pkgs = gsub("\\(.*)", "", pkgs) # Remove versions from packages
ext_pkgs = c("rio", "feather")  # issues installing on travis
pkgs = c(pkgs, ext_pkgs)
pkgs = unique(pkgs)

if(!all(ext_pkgs %in% rownames(installed.packages()))) {
  message("Installing rio and feather")
  install.packages(ext_pkgs, repos="http://cran.rstudio.com/")
}

i = 1
pkgs = pkgs[order(pkgs)]
pkgs_df = data.frame(Name = pkgs, Title = NA, cite=NA, version=NA)
for(i in seq_along(pkgs)){
  f = system.file(package = pkgs[i], "DESCRIPTION")
  # Title is always on 3rd line
  title = readLines(f)
  title = title[grep("Title: ", title)]
  pkgs_df$Title[i] = gsub("Title: ", "", title)
  pkgs_df$cite[i] = paste0("[@R-", pkgs[i], "]")
  pkgs_df$version[i] = as.character(packageVersion(pkgs[i]))
}
pkgs_df[,2] = paste(pkgs_df[,2], pkgs_df[,3])
pkgs_df = pkgs_df[,-3]
write.csv(pkgs_df, "extdata/package_list.csv", row.names = FALSE)
knitr::write_bib(pkgs, file="packages.bib")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::kable(pkgs_df)
```

# References {-}
