--- 
title: "Efficient R programming"
author: "Colin Gillespie and Robin Lovelace"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
output:
  bookdown::html_chapters:
    css: style.css
    md_extensions: +markdown_in_html_blocks
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    latex_engine: xelatex
documentclass: book
bibliography: refs.bib
biblio-style: apalike
link-citations: yes
---

<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>


__Dependencies for this book__

This book has been written in **Markdown** and was built with the bookdown package.

This book has been written in **Markdown** and was built with the bookdown package. 
The html version is also [available](https://csgillespie.github.io/efficientR/). 
Pull requests are welcome.

To build this book, the following packages must be installed.

```{r eval=FALSE}
pkgs = c(
  "numbers", "dplyr", "readxl",
  "readr", "grid", "png",
  "rbenchmark", "microbenchmark",
  "fortunes", "pryr", "ggplot2")

to_install = pkgs[!pkgs %in% installed.packages()]
if(length(to_install))
  install.packages(to_install)
```

GitHub packages to install.

```{r eval=FALSE}
gh_pkgs = c("csgillespie/efficient_pkg", "rstudio/bookdown")
devtools::install_github(gh_pkgs)
```






 
